version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    command: flask run --host 0.0.0.0 --port 3000
    environment:
      - FLASK_APP=hello.py